version: '3.6'

services:
  svc:
    build: .
    restart: unless-stopped
    ports:
      - 3001:80
    volumes:
      - ./src:/app
      - ./html:/html
  svc-nosql:
    image: 'mongo:4.2.3-bionic'
    environment:
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_ROOT_USERNAME=root
  svc-nosql-express:
    image: mongo-express
    ports:
      - 3002:8081
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
      - ME_CONFIG_MONGODB_SERVER=svc-nosql